# Generated by Django 5.2.1 on 2025-05-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("norad_id", models.IntegerField(unique=True)),
                (
                    "intl_designator",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("time_of_closest_approach", models.DateTimeField()),
                ("miss_distance_km", models.FloatField()),
                ("collision_probability", models.FloatField()),
                (
                    "satellite_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_as_sat1",
                        to="core.satellite",
                    ),
                ),
                (
                    "satellite_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_as_sat2",
                        to="core.satellite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TLEEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(max_length=100)),
                ("line2", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tle_entries",
                        to="core.satellite",
                    ),
                ),
            ],
        ),
    ]
