# Generated by Django 5.2.1 on 2025-07-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sat1_id", models.CharField(max_length=255)),
                ("sat2_id", models.CharField(max_length=255)),
                ("miss_distance", models.FloatField()),
                ("probability", models.FloatField()),
                ("tca", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
