# Generated by Django 5.2.1 on 2026-05-09 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionreport',
            name='avg_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='relative_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='risk_label',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='risk_probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='sat1_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='sat2_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='time_to_tca_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
